### PR TITLE
Dw tick8 computerresource

### LINKED ISSUE #8: Allow developers to access the Computer resource
Verbs to be supported

1. GET
1. POST
1. PUT
1. DELETE

User should be able to GET a list, and GET a single item.

### PR DESCRIPTION
**Pull request by CosignMyCodesign**
## Link to Ticket
Closes #8 

## Description of Proposed Changes
Completed the serializer and viewset for the Computer Resource. Anyone viewing the browseable API can do a GET for the computer list or a single computer. They can also perform a PUT, POST, and DELETE method. I also edited the root to be api/v1/
- 

## Steps to Test

- Pull down the code

- open localhost:8000/api/v1/

- click the computer url to view the computer list

- perform a POST to test if a new computer can be posted

- click the url for a singular computer instance and perform a PUT and DELETE

```sh
git fetch --all
git checkout dw-tick8_computerresource
```

## Impacted Areas in Application

List general components of the application that this PR will affect:

*Computers Resource

### CODE REVIEW

**Comment by jessicabarnett8219** [comment]
Your code looks great but I realized when trying to post a new computer that decommission date cannot be left blank. We need to change that in our model.

**Review by rjlancaster — COMMENTED** [review]
I had the same thing happen as Jessica.  Prolly just need to change the model and re-migrate.  Everything else works though.

**Comment by jessicabarnett8219** [comment]
👍

**Comment by Kazathur92** [comment]
👍

**Pull request merged**
