### PR TITLE
Ticket5 product type view

### PR DESCRIPTION
**Pull request by Kazathur92**
## Link to Ticket
Closes # [https://github.com/blathering-barnacles/Bangazon-3/issues/5](Ticket5)

## Description of Proposed Changes
Added the ability to view all the productTypes, and a single product type, delete it and edit it.
- 

## Steps to Test

go to localhost:8000 and click on the ProductType url
go to localhost:8000/productType and click on a productType url

```sh
git fetch --all
git checkout ticket5_productTypeView
```

## Impacted Areas in Application

List general components of the application that this PR will affect:

* ProductType Resource

### CODE REVIEW

**Review by Andrew-Herring — APPROVED** [review]
Looks good to me 👍

**Review by rjlancaster — APPROVED** [review]
👍 works for me!

**Comment by jessicabarnett8219** [comment]
Also, the only actions that should be GET PUT POST DELETE, so you'll need to take off patch, head and options

**Comment by jessicabarnett8219** [comment]
👍

**Pull request merged**
